<?php
$json = $this->params()->fromQuery('json') ? $this->params()->fromQuery('json') : $this->params()->fromPost('json', '');
if($json){
    echo $this->content;
    return ;
}

$translate = $this->plugin('translate');
$this->headMeta()->setCharset('utf-8');

$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Source+Code+Pro|Lato:400,400italic,700,700italic');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');

$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));

$this->headScript()->appendFile($this->assetUrl("js/d3.v7.min.js"));
$this->headScript()->appendFile($this->assetUrl("js/bootstrap5.3.bundle.min.js"));
$this->headScript()->appendFile($this->assetUrl("js/main.js"));
$this->headScript()->appendFile($this->assetUrl("js/handsontable.full.min.js"));
$this->headScript()->appendFile($this->assetUrl("js/video.min.js"));
$this->headScript()->appendFile($this->assetUrl("js/howler.min.js"));  
$this->headScript()->appendFile($this->assetUrl("js/d3.layout.cloud.js"));
$this->headScript()->appendFile("https://kit.fontawesome.com/41992aa5bc.js");

$this->headLink()->appendStylesheet($this->assetUrl('css/bootstrap5.3.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/menu.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/all.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/handsontable.full.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/main.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/video-js.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/nouislider.min.css'));

$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', $this->lang()); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <?php echo $this->htmlElement('body')->appendAttribute('class', 'minimal'); ?>
        <body class="d-flex h-100 text-center text-white bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">


    <header>
        <div>
            <nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark border-bottom border-bottom-dark"
                data-bs-theme="dark">
                <?php
                echo $site->publicNav()->menu()->renderMenu(null, [
                    'maxDepth' => 0
                ]);
                echo $userBar;
            ?>
            </nav>

        </div>
    </header>


    <main id='mainContent'>

        <div class="container-fluid text-center">
            <div class="row my-2">
                <?php echo $this->messages(); ?>
                <?php echo $this->content; ?>              
            </div>
        </div>
    </main>

    <footer class="mt-auto text-white-50">
        <p style="padding-top: 6px;">Design by <a href="https://samszo.univ-paris8.fr/" class="text-white">Samuel
                Szoniecky</a>
            <a target="_blank" href="https://www.univ-paris8.fr/EA-349-Laboratoire-Paragraphe">
                <img style="height: 40px;" src="<?php echo $this->assetUrl('img/logo-paragraphe-blanc.svg'); ?>"
                    alt="Laboratoire Paragraphe" />
            </a>
            <a target="_blank" href="https://github.com/samszo/HDR">
                <button type="button" class="btn btn-danger">
                    <i class="fa-brands fa-github fa-2xl"></i>
                </button>
            </a>
            Template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a
                href="https://twitter.com/mdo" class="text-white">@mdo</a>.
        </p>
    </footer>

</div>


<div id="loading-container">
    <div class="loadingio-spinner-double-ring-4dols36ufwg" id="ws-loading">
        <div class="ldio-6pd26u1x99x">
            <div></div>
            <div></div>
            <div>
                <div></div>
            </div>
            <div>
                <div></div>
            </div>
        </div>
    </div>
</div>

<script type="module">
import {loader} from '<?php echo $this->assetUrl('modules/loader.js'); ?>';
let wait = new loader();
wait.hide();

</script>

    </body>
</html>
